def load_info_boxes():
    """
    Loads the list of wiki bio info boxes.
    :return: a list of all wiki bio info boxes
    """
    return [
        "Infobox person",
        "Infobox Buddha",
        "Infobox Christian leader",
        "Infobox clergy",
        "Infobox Jewish leader",
        "Infobox Latter Day Saint biography",
        "Infobox religious biography",
        "Infobox saint",
        "Infobox Egyptian dignitary",
        "Infobox noble",
        "Infobox pharaoh",
        "Infobox pretender",
        "Infobox royalty",
        "Infobox college football player",
        "Infobox Canadian Football League biography",
        "Infobox NFL biography",
        "Infobox football biography",
        "Infobox football official",
        "Infobox baseball biography",
        "Infobox basketball biography",
        "Infobox ice hockey biography",
        "Infobox Champ Car driver",
        "Infobox F1 driver",
        "Infobox Le Mans driver",
        "Infobox Motocross rider",
        "Infobox motorcycle rider",
        "Infobox NASCAR driver",
        "Infobox racing driver",
        "Infobox racing driver series section",
        "Infobox speedway rider",
        "Infobox WRC driver",
        "Infobox sportsperson",
        "Infobox biathlete",
        "Infobox boxer (amateur)",
        "Infobox climber",
        "Infobox professional bowler",
        "Infobox sailor",
        "Infobox speed skater",
        "Infobox sport wrestler",
        "Infobox swimmer",
        "Infobox bullfighting career",
        "Infobox AFL biography",
        "Infobox alpine ski racer",
        "Infobox amateur wrestler",
        "Infobox badminton player",
        "Infobox bandy biography",
        "Infobox bodybuilder",
        "Infobox boxer",
        "Infobox cricketer",
        "Infobox curler",
        "Infobox cyclist",
        "Infobox equestrian",
        "Infobox fencer",
        "Infobox field hockey player",
        "Infobox figure skater",
        "Infobox Gaelic Athletic Association player",
        "Infobox golfer",
        "Infobox gymnast",
        "Infobox handball biography",
        "Infobox horseracing personality",
        "Infobox lacrosse player",
        "Infobox martial artist",
        "Infobox mountaineer",
        "Infobox NCAA athlete",
        "Infobox netball biography",
        "Infobox pelotari",
        "Infobox professional wrestler",
        "Infobox rugby biography",
        "Infobox rugby league biography  Holding cell",
        "Infobox skier",
        "Infobox sports announcer details",
        "Infobox squash player",
        "Infobox sumo wrestler",
        "Infobox surfer",
        "Infobox table tennis player",
        "Infobox tennis biography",
        "Infobox volleyball biography",
        "Infobox person",
        "Infobox academic",
        "Infobox architect",
        "Infobox artist",
        "Infobox art historian",
        "Infobox chef",
        "Infobox clergy",
        "Infobox classical composer",
        "Infobox criminal",
        "Infobox dancer",
        "Infobox economist",
        "Infobox engineer",
        "Infobox engineering career",
        "Infobox medical details",
        "Infobox medical person",
        "Infobox model",
        "Infobox pageant titleholder",
        "Infobox philosopher",
        "Infobox pirate",
        "Infobox police officer",
        "Infobox presenter",
        "Infobox scientist",
        "Infobox sports announcer",
        "Infobox spy",
        "Infobox theologian",
        "Infobox theological work",
        "Infobox astronaut",
        "Infobox aviator",
        "Infobox chess biography",
        "Infobox college coach",
        "Infobox comedian",
        "Infobox comics creator",
        "Infobox darts player",
        "Infobox FBI Ten Most Wanted",
        "Infobox go player",
        "Infobox Magic: The Gathering player",
        "Infobox military person",
        "Infobox musical artist",
        "Infobox Nahua officeholder",
        "Infobox officeholder",
        "Infobox Native American leader",
        "Infobox Playboy Playmate",
        "Infobox poker player",
        "Infobox snooker player",
        "Infobox video game player",
        "Infobox War on Terror detainee",
        "Infobox writer",
        "Infobox YouTube personality"
    ]